# Script and App dependencies
# Create conda env: conda env create -f scripts/requirements.yaml
# Activate: conda activate cryptography-scripts
name: cryptography-scripts
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.10
  - pip
  - pip:
    - streamlit
    - pyyaml
    - extra-streamlit-components
    - pytest
